version: "3.9"

services:
  app:
    image: go_todo
    build:
      args:
        - target=dev
    environment:
      TODO_ENV: dev
      PORT: 8080
    volumes:
      - .:/app
    ports:
      - "8080:8080"